Does not compile now if both WRF_EM_CORE and WRF_NMM_CORE are set to 0 (fix for user bug reports that compile appears fine but run error is dyn_opt=0, per DG). JA
git-svn-id: https://svn-wrf-model.cgd.ucar.edu/trunk@282 b0b5d27b-6f0f-0410-a2a3-cb1e977edc3d

diff --git a/compile b/compile
--- a/compile
+++ b/compile
@@ -63,6 +63,10 @@ else
     echo "Cannot compile both EM and NMM cores in same executable yet."
     exit 2
   endif
+  if ($WRF_EM_CORE == 0 && WRF_NMM_CORE == 0 ) then
+    echo "Cannot compile because both EM and NMM cores are set to 0."
+    exit 2
+  endif
   if ($WRF_EM_CORE == 1)  then
     if ( ! -f Registry/Registry ) then
       set overwrite=1
@@ -135,14 +139,18 @@ exit 0
 
 hlp:
 
+echo ' '
 echo 'Usage:'
-echo '  compile wrf           compile wrf in run dir'
-echo '  test cases (see README_test_cases):'
+echo ' '
+echo '   compile wrf           compile wrf in run dir (no preprocessors)'
+echo ' '
+echo '   or choose a test case (see README_test_cases for details) :'
 foreach d ( `/bin/ls test` )
   if ( "$d" != "CVS" ) then
-    echo "   compile $d"
+    echo "      compile $d"
   endif
 end
+echo ' '
 echo '  compile -h                 help message'
 
 
