There is an emergency commit for adding -m32/m64 option on fly by configure script. It has already been discussed. And I have been in contact with Wei, Michael, and Dave. Dave is OK with this emergency commit.
1) Fixed the logic issues. It now can correctly identify  the case that the user has a C compiler that supports cross-compiling and a Fortran compiler that doesn't (or vice versa)
2) Using mktemp to ensure that all testing is done with a unique temporary file name
3) Cleaning all the files used by testing completely
4) Adding prompt messages to tell user some test is going on



git-svn-id: https://svn-wrf-model.cgd.ucar.edu/trunk@4846 b0b5d27b-6f0f-0410-a2a3-cb1e977edc3d

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -552,159 +552,198 @@ if [ "$wrf_core" = "DA_CORE" ]; then
   fi
 fi
 
-echo 
-
 #Checking cross-compiling capability for some particular environment 
 #on Linux and Mac box
-#set -x
 
 if [ $os = "Linux" -o $os = "Darwin" ]; then
-  #echo "1.  OS = " $os
 
   SFC=`grep '^SFC' configure.wrf | awk '{print $3}'`
   SCC=`grep '^SCC' configure.wrf | awk '{print $3}'`
+  CCOMP=`grep '^CCOMP' configure.wrf | awk '{print $3}'`
 
   SFC="`type $SFC 2>/dev/null | awk '{print $NF}' | sed -e 's/(//g;s/)//g'`"
   SCC="`type $SCC 2>/dev/null | awk '{print $NF}' | sed -e 's/(//g;s/)//g'`"
+  CCOMP="`type $CCOMP 2>/dev/null | awk '{print $NF}' | sed -e 's/(//g;s/)//g'`"
 
-  #echo "2. SFC = " $SFC
-  #echo "3. SCC = " $SCC
-
-  if [ -e $NETCDF/lib/libnetcdf.a -a "$SFC" != "" -a "$SCC" != "" ]; then
-
-    cp configure.wrf configure.wrf.edit
-   
-    #echo "4. Checking cross-compiling"
+  if [ -e $NETCDF/lib/libnetcdf.a -a "$SFC" != "" -a "$SCC" != "" -a "$CCOMP" != "" ]; then
 
     SFC_MULTI_ABI=0
     SCC_MULTI_ABI=0
+    CCOMP_MULTI_ABI=0
     CROSS_COMPILING=0
 
-cat > /tmp/test.c <<EOF 
+    foo=`mktemp foo_$$`
+
+    echo
+    echo Testing for NetCDF, C and Fortran compiler
+    echo
+
+cat > ${foo}.c <<EOF 
  int main(int argc, char ** argv)
  {
      return (0);
  }
 EOF
 
-cat > /tmp/test.f <<EOF
+cat > ${foo}.f <<EOF
           program test_exit
             integer :: STATUS = 0
             call EXIT(STATUS)
           end program test_exit
 EOF
 
-    ar p $NETCDF/lib/libnetcdf.a netcdf.o > /tmp/netcdf.o
-    netcdf_arch="`file /tmp/netcdf.o | grep -o -E '[0-9]{2}-bit|i386'`"
-    rm /tmp/netcdf.o
+    ar p $NETCDF/lib/libnetcdf.a netcdf.o > ${foo}.o
+    netcdf_arch="`file ${foo}.o | grep -o -E '[0-9]{2}-bit|i386'`"
+    rm ${foo}.o
 
-    $SFC -o /tmp/a.out /tmp/test.f > /dev/null 2>&1 
-    SFC_arch="`file /tmp/a.out | grep -o -E '[0-9]{2}-bit|i386'`"
-    rm /tmp/a.out 2> /dev/null
+    $SFC -o ${foo} ${foo}.f > /dev/null 2>&1 
+    SFC_arch="`file ${foo} | grep -o -E '[0-9]{2}-bit|i386'`"
+    rm ${foo} 2> /dev/null
 
-    $SCC -o /tmp/a.out /tmp/test.c > /dev/null 2>&1
-    SCC_arch="`file /tmp/a.out | grep -o -E '[0-9]{2}-bit|i386'`"
-    rm /tmp/a.out 2> /dev/null
+    $SCC -o ${foo} ${foo}.c > /dev/null 2>&1
+    SCC_arch="`file ${foo} | grep -o -E '[0-9]{2}-bit|i386'`"
+    CCOMP_arch=$SCC_arch
+    rm ${foo} 2> /dev/null
+
+    if [ "$SCC" != "$CCOMP" ]; then
+      $CCOMP -o ${foo} ${foo}.c > /dev/null 2>&1
+      CCOMP_arch="`file ${foo} | grep -o -E '[0-9]{2}-bit|i386'`"
+      rm ${foo} 2> /dev/null
+    fi
+
+    if [ "$SFC_arch" = "" -o "$SCC_arch" = "" -o "$CCOMP_arch" = "" ]; then
+      echo "  One of compilers testing failed!"
+      echo "  Please check your compiler"
+      echo 
+      rm ${foo}* 2> /dev/null
+      exit
+    else
+      cp configure.wrf configure.wrf.edit
+    fi
 
     case $netcdf_arch in
 
       32-bit|i386 )
 
-      #echo "5. netcdf_arch = " $netcdf_arch
       if [ "$SFC_arch" = "64-bit" ] ; then
-        #echo "5.1 SFC_arch = " $SFC_arch
         CROSS_COMPILING=1
-        $SFC -m32 -o /tmp/a.out /tmp/test.f > /dev/null 2>&1
+        $SFC -m32 -o ${foo} ${foo}.f > /dev/null 2>&1
         if [ $? = 0 ]; then
-          #echo "5.1.1 Adding -m32 option for $SFC"
           SFC_MULTI_ABI=1
-          sed '/^SFC *=/s/.*/& -m32/' configure.wrf.edit > configure.wrf.tmp
+          sed '/^SFC.*=/s/$/ -m32/' configure.wrf.edit > configure.wrf.tmp
           mv configure.wrf.tmp configure.wrf.edit
         fi
-        rm /tmp/test.f /tmp/a.out 2> /dev/null
       fi
       if [ "$SCC_arch" = "64-bit" ] ; then
-        #echo "5.2 SCC_arch = " $SCC_arch
         CROSS_COMPILING=1
-        $SCC -m32 -o /tmp/a.out /tmp/test.c > /dev/null 2>&1
+        $SCC -m32 -o ${foo} ${foo}.c > /dev/null 2>&1
         if [ $? = 0 ]; then
-          #echo "5.2.1 Adding -m32 option for $SCC"
           SCC_MULTI_ABI=1
-          sed '/^SCC *=/s/.*/& -m32/' configure.wrf.edit > configure.wrf.tmp
-          sed '/^CCOMP *=/s/.*/& -m32/' configure.wrf.tmp > configure.wrf.edit
-          rm configure.wrf.tmp
+          sed '/^SCC.*=/s/$/ -m32/' configure.wrf.edit > configure.wrf.tmp
+          mv configure.wrf.tmp  configure.wrf.edit
         fi
-        rm /tmp/test.c /tmp/a.out 2> /dev/null
+      fi
+
+      if [ "$CCOMP_arch" = "64-bit" ] ; then
+        CROSS_COMPILING=1
+        if [ "$CCOMP" != "$SCC" ]; then
+          $CCOMP -m32 -o ${foo} ${foo}.c > /dev/null 2>&1
+          if [ $? = 0 ]; then
+            CCOMP_MULTI_ABI=1
+            sed '/^CCOMP/ s/$/ -m32/' configure.wrf.edit > configure.wrf.tmp
+            mv configure.wrf.tmp  configure.wrf.edit
+          fi
+        else
+          CCOMP_MULTI_ABI=1
+          sed '/^CCOMP/ s/$/ -m32/' configure.wrf.edit > configure.wrf.tmp
+          mv configure.wrf.tmp  configure.wrf.edit
+        fi
       fi
 
       if [ $CROSS_COMPILING -eq 1 ] ; then
-        #echo " 5.3 Show Cross-compiling capability"
-        #echo "\033[1;31mNOTE:\033[m"
-        echo $NETCDF/lib/libnetcdf.a is 32-bit
-        if [ $SFC_MULTI_ABI -ne 1 -o  $SCC_MULTI_ABI -ne 1 ] ; then
-           if  [ "$SFC_arch" = "64-bit" -a "$SCC_arch" = "64-bit" ]; then
-             echo One of compilers doesn\'t support cross-compiling.
+        echo NOTE:
+        echo This installation NetCDF is 32-bit
+        if [ \( $SFC_MULTI_ABI -ne 1 -a "$SFC_arch" = "64-bit" \) \
+             -o \( $SCC_MULTI_ABI -ne 1 -a "$SCC_arch" = "64-bit" \) \
+             -o \( $CCOMP_MULTI_ABI -ne 1 -a "$CCOMP_arch" = "64-bit" \) ] ; then
+             rm configure.wrf.edit
+             echo One of compilers is 64-bit and doesn\'t support cross-compiling.
              echo Please check your NETCDF lib and compiler
-           else
-            echo -m32 is appended to configure.wrf
-            echo It will be forced to build in 32-bit.
-          fi
         else
           echo -m32 is appended to configure.wrf
           echo It will be forced to build in 32-bit.
+          echo If you don\'t want 32-bit binaries, please use 64-bit NetCDF, and re-run the configure script.
         fi
       fi
       ;;
 
       64-bit )
 
-      #echo "6. netcdf_arch = " $netcdf_arch
       if [ "$SFC_arch" = "32-bit" -o "$SFC_arch" = "i386" ] ; then
-        #echo "6.1 SFC_arch = " $SFC_arch
         CROSS_COMPILING=1
-        $SFC -m64 -o /tmp/a.out /tmp/test.f > /dev/null 2>&1
+        $SFC -m64 -o ${foo} ${foo}.f > /dev/null 2>&1
         if [ $? = 0 ]; then
-          echo "6.1.1 Adding -m64 option for $SFC"
           SFC_MULTI_ABI=1
-          sed '/^SFC *=/s/.*/& -m64/' configure.wrf.edit > configure.wrf.tmp
+          sed '/^SFC.*=/s/$/ -m64/' configure.wrf.edit > configure.wrf.tmp
           mv configure.wrf.tmp configure.wrf.edit
         fi
-        rm /tmp/a.out /tmp/test.f 2> /dev/null
       fi
       if [ "$SCC_arch" = "32-bit" -o "$SCC_arch" = "i386" ] ; then
-        #echo "6.2 SCC_arch = " $SCC_arch
         CROSS_COMPILING=1
-        $SCC -m64 -o /tmp/a.out /tmp/test.c > /dev/null 2>&1
+        $SCC -m64 -o ${foo} ${foo}.c > /dev/null 2>&1
         if [ $? = 0 ]; then
-          #echo "6.2.1 Adding -m64 option for $SCC"
           SCC_MULTI_ABI=1
-          sed '/^SCC *=/s/.*/& -m64/' configure.wrf.edit > configure.wrf.tmp
-          sed '/^CCOMP *=/s/.*/& -m64/' configure.wrf.tmp > configure.edit
-          rm configure.wrf.tmp
+          sed '/^SCC.*=/s/$/ -m64/' configure.wrf.edit > configure.wrf.tmp
+          mv configure.wrf.tmp configure.wrf.edit
         fi
-        rm /tmp/a.out /tmp/test.c 2> /dev/null
-     fi
+      fi
+
+      if [ "$CCOMP_arch" = "32-bit" -o "$CCOMP_arch" = "i386" ] ; then
+        CROSS_COMPILING=1
+        if [ "$CCOMP" != "$SCC" ]; then
+          $CCOMP -m64 -o ${foo} ${foo}.c > /dev/null 2>&1
+          if [ $? = 0 ]; then
+            CCOMP_MULTI_ABI=1
+            sed '/^CCOMP/ s/$/ -m64/' configure.wrf.edit > configure.wrf.tmp
+            mv configure.wrf.tmp  configure.wrf.edit
+          fi
+        else
+          CCOMP_MULTI_ABI=1
+          sed '/^CCOMP/ s/$/ -m64/' configure.wrf.edit > configure.wrf.tmp
+          mv configure.wrf.tmp  configure.wrf.edit
+        fi
+      fi
 
       if [ $CROSS_COMPILING -eq 1 ] ; then
-        #echo "6.3 Showing Cross-compiling capability"
-        #echo "\033[1;31mNOTE:\033[m"
-        echo $NETCDF/lib/libnetcdf.a is 64-bit
-        if [ $SFC_MULTI_ABI -ne 1  -o  $SCC_MULTI_ABI -ne 1 ]; then
-          if [ "$SFC_arch" != "64-bit" -a "$SCC_arch" != "64-bit" ]; then
-            echo One of Compilers doesn\'t support cross-compiling.
-            echo Please check your NETCDF lib and compiler
-          else
-            echo -m64 is appended to configure.wrf
-            echo It will be forced to build in 64-bit.
-          fi
+        echo NOTE:
+        echo This installation NetCDF is 64-bit
+        if [ \( $SFC_MULTI_ABI -ne 1 -a "$SFC_arch" != "64-bit" \) \
+            -o \( $SCC_MULTI_ABI -ne 1 -a "$SCC_arch" != "64-bit" \) \
+            -o \( $CCOMP_MULTI_ABI -ne 1 -a "CCOMP_arch" != "64-bit" \) ]; then
+            rm configure.wrf.edit
+            echo One of Compilers is 32-bit and doesn\'t support cross-compiling.
+            echo Please check your NetCDF lib and compiler
         else
           echo -m64 is appended to configure.wrf
           echo It will be forced to build in 64-bit. 
+          echo If you don\'t want 64-bit binaries, please use 32-bit NetCDF, and re-run the configure script.
         fi
       fi
       ;;
     esac
-    mv configure.wrf.edit configure.wrf
+
+    if [ -e configure.wrf.edit ]; then 
+      mv configure.wrf.edit configure.wrf
+    fi
+
+    rm ${foo}* 2> /dev/null
+
+    if [ $CROSS_COMPILING -eq 0 ] ; then
+      echo This installation NetCDF is $netcdf_arch
+      echo C compiler is $SCC_arch
+      echo Fortran compiler is $SFC_arch
+      echo It will build in $netcdf_arch
+    fi
+    echo
   fi
 fi
-echo
