>>>>>>>>>>>>>>WRFPLUS Branch Commit<<<<<<<<<<<<<
svn merge -r7456:7760 https://svn-wrf-model.cgd.ucar.edu/trunk .

The following TL/AD codes are modified.
M    share/module_bc_tl.F
M    dyn_em/solve_em_tl.F
M    dyn_em/module_first_rk_step_part1_ad.F
M    dyn_em/start_em_tl.F
M    dyn_em/module_diffusion_em_tl.F
M    dyn_em/solve_em_ad.F
M    dyn_em/module_first_rk_step_part1_tl.F

On yellowstone (ifort compiler), TL/AD check and regression test case
produced the same results as previous versions.

However, I do not think the current TL/AD check results are correct.
Also, with pgi compiler on Mac Mavericks, the results are very different
from those on yellowstone.



git-svn-id: https://svn-wrf-model.cgd.ucar.edu/branches/WRFPLUSV3@7782 b0b5d27b-6f0f-0410-a2a3-cb1e977edc3d

Former-commit-id: c63ee4d3d10d270daba81603aa0057a3025a395c

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -553,8 +553,24 @@ if [ -n "$WRF_NMM_CORE" -a -n "$WRF_CHEM" ]; then
   fi
 fi
 
-if [ `which timex` ] ; then
+type m4 > /dev/null
+if [ $? -ne 0 ] ; then
+  echo
+  echo "ERROR ERROR ERROR ERROR ERROR ERROR ERROR"
+  echo "'m4' utility not found! Can not configure."
+  echo
+  echo "If on an Ubuntu machine, use the command"
+  echo "         sudo apt-get install m4        "
+  echo "To download and install the 'm4' utility"
+  exit 1
+fi
+
+if command -v timex > /dev/null 2>&1; then
   FORTRAN_COMPILER_TIMER=timex
+  echo "Will use 'timex' to report timing information"
+elif command -v time > /dev/null 2>&1; then
+  FORTRAN_COMPILER_TIMER=time
+  echo "Will use 'time' to report timing information"
 fi
 
 # Found perl, so proceed with configuration
@@ -566,6 +582,7 @@ if test -n "$PERL" ; then
           -compileflags=$compileflags -opt_level=$opt_level -USENETCDFF=$USENETCDFF -time=$FORTRAN_COMPILER_TIMER \
           -wrf_core=$wrf_core -gpfs=$GPFS_PATH -curl=$CURL_PATH -dep_lib_path="$DEP_LIB_PATH"
      if test ! -f configure.wrf ; then
+       echo "configure.wrf not created! Exiting configure script..."
        exit 1
      fi
      if [ "$opt_level" = "-d" ] ; then
@@ -955,6 +972,48 @@ if [ $retval -ne 0 ] ; then
   echo "That may not be enough."
   echo " "
   echo "*****************************************************************************"
+fi
+
+# testing for Fortran 2003 FLUSH features
+make fortran_2003_flush_test > tools/fortran_2003_flush_test.log 2>&1
+rm -f tools/fortran_2003_flush_test.log
+retval=-1
+if [ -f tools/fortran_2003_flush_test.exe ] ; then
+  retval=0
+fi
+if [ $retval -ne 0 ] ; then
+  make fortran_2003_fflush_test > tools/fortran_2003_fflush_test.log 2>&1
+  rm -f tools/fortran_2003_fflush_test.log
+  retval=-1
+  if [ -f tools/fortran_2003_fflush_test.exe ] ; then
+    retval=0
+  fi
+  if [ $retval -eq 0 ] ; then
+    sed -e '/^ARCH_LOCAL/s/$/ -DUSE_FFLUSH/' configure.wrf > configure.wrf.edit
+    mv configure.wrf.edit configure.wrf
+    echo " "
+    echo " "
+    echo "************************** W A R N I N G ************************************"
+    echo " "
+    echo "There are some Fortran 2003 features in WRF that your compiler does not recognize"
+    echo "The standard FLUSH routine has been replaced by FFLUSH."
+    echo "That may not be enough."
+    echo " "
+    echo "*****************************************************************************"
+  fi
+  if [ $retval -ne 0 ] ; then
+    sed -e '/^ARCH_LOCAL/s/$/ -DNO_FLUSH_SUPPORT/' configure.wrf > configure.wrf.edit
+    mv configure.wrf.edit configure.wrf
+    echo " "
+    echo " "
+    echo "************************** W A R N I N G ************************************"
+    echo " "
+    echo "There are some Fortran 2003 features in WRF that your compiler does not recognize"
+    echo "The standard FLUSH routine has been stubbed out."
+    echo "That may not be enough."
+    echo " "
+    echo "*****************************************************************************"
+  fi
 fi
 
 # testing for netcdf4 IO features
