Build fixes, mostly from John.  Pathscale stanza added.  Bug fix for CC=CC_TOOLS in top level Makefile.  CPP redefinition for chem/Makefile removed.
M    configure
M    compile
M    chem/Makefile
A    arch/postamble_old
A    arch/configure_old.defaults
A    arch/preamble_old
D    arch/postamble
M    arch/configure.defaults
D    arch/preamble
M    arch/Config_new.pl
M    arch/postamble_new
M    arch/configure_new.defaults
AM   arch/config_old
A    arch/Config_old.pl
M    Makefile
D    config_new



git-svn-id: https://svn-wrf-model.cgd.ucar.edu/trunk@2927 b0b5d27b-6f0f-0410-a2a3-cb1e977edc3d

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,6 +1,33 @@
 #!/bin/sh
 
-arg1=$1
+# parse argument list
+
+thiscmd=$0
+
+opt_level="-s"
+print_usage=""
+chemistry=""
+while [ $# -ge 1 ]; do
+    case $1 in
+      -d) opt_level="-d" ;;
+      -s) opt_level="-s" ;;
+      -f) opt_level="-f" ;;
+      -h) print_usage="yes" ;;
+      -help) print_usage="yes" ;;
+      -os) shift ; WRF_OS=$1 ;;
+      -mach) shift ; WRF_MACH=$1 ;;
+      chem) WRF_CHEM=1  ;;
+      kpp) WRF_KPP=1  ;;
+      titan) WRF_TITAN=1 ; break ;;
+      mars) WRF_MARS=1 ; break ;;
+      venus) WRF_VENUS=1 ; break ;;
+    esac
+    shift
+done
+if [ -n "$print_usage" ] ; then
+  echo usage: $thiscmd '[-d|-s|-f|-os os|-mach mach] [chem] [kpp]'
+  exit 
+fi
 
 # lifted from the configure file for mpich; 00/03/10 jm
 #
@@ -225,8 +252,14 @@ if test -z "$PDHF5" ; then
   fi
 fi
 
+USENETCDFF=""  # see below
 if [ -n "$NETCDF" ] ; then
   echo "Will use NETCDF in dir: $NETCDF"
+# for 3.6.2 and greater there might be a second library, libnetcdff.a .  Check for this and use 
+# if available
+  if [ -f "$NETCDF/lib/libnetcdff.a" ] ; then
+    USENETCDFF="-lnetcdff"
+  fi
 else
   echo "Will configure for use without NetCDF"
 fi
@@ -292,7 +325,7 @@ if [ "$os" = "AIX" ] ; then
 fi
 
 # compile options that come from the environment, such as chemistry
-# the "!" is removed by Config.pl
+# the "!" is removed by Config_new.pl
 if [ -n "$WRF_MARS" ] ; then
   if [ $WRF_MARS = 1 ] ; then
     echo building WRF for Mars
@@ -319,11 +352,11 @@ if [ -n "$WRF_CHEM" ] ; then
     echo building WRF with chemistry option
     compileflags="${compileflags}!-DWRF_CHEM"
     if [ -n "$WRF_KPP" ] ; then
-      if [ $WRF_KPP = 1 ] ; then
+      if [ $WRF_KPP = 1 ] ; then    
         echo building WRF with KPP chemistry option
         compileflags="${compileflags}!-DWRF_KPP"
       fi
-    fi
+    fi 
   else
     compileflags="${compileflags} "
   fi
@@ -333,18 +366,29 @@ fi
 
 # Found perl, so proceed with configuration
 if test -n "$PERL" ; then
-   $PERL arch/Config.pl -perl=$PERL -netcdf=$NETCDF -pnetcdf=$PNETCDF -phdf5=$PHDF5 -os=$os -mach=$mach -ldflags=$ldflags \
-   -compileflags=$compileflags
-  if test ! -f configure.wrf ; then
-    exit 1
-  fi
-fi
-
-if [ "$arg1" = "-d" ] ; then
-ls -l configure.wrf
-   if [ -e configure.wrf ] ; then
-     sed -e 's/FCOPTIM[	  ]*=/& # /' -e '/FCDEBUG[ 	]*=/s/#//g' configure.wrf > configure.wrf.edit
-     /bin/mv configure.wrf.edit configure.wrf
+   srch=`grep -i "^#ARCH.*$os" arch/configure_new.defaults | grep -i "$mach"`
+   if [ -n "$srch" ] ; then
+     $PERL arch/Config_new.pl -dmparallel=$COMMLIB -ompparallel=$OMP -perl=$PERL \
+          -netcdf=$NETCDF -pnetcdf=$PNETCDF -phdf5=$PHDF5 -os=$os -mach=$mach -ldflags=$ldflags \
+          -compileflags=$compileflags -opt_level=$opt_level -USENETCDFF=$USENETCDFF
+     if test ! -f configure.wrf ; then
+       exit 1
+     fi
+     if [ "$opt_level" = "-d" ] ; then
+#       ls -l configure.wrf
+        sed -e 's/FCOPTIM[	  ]*=/& # /' -e '/FCDEBUG[ 	]*=/s/#//g' configure.wrf > configure.wrf.edit
+        /bin/mv configure.wrf.edit configure.wrf
+     fi
+   else
+     WRF_OS=$os ; export WRF_OS
+     WRF_MACH=$mach ; export WRF_MACH
+     echo '*** Configuration not found in configure_new.defaults; checking configure_old.defaults ***'
+     # see if we still have an old setting laying around from v2
+     if [ "$opt_level" = "-d" ] ; then
+       arch/config_old $opt_level 
+     else
+       arch/config_old
+     fi
    fi
 fi
 
@@ -357,7 +401,7 @@ if test -f configure.wrf ; then
     ( make mpi2_test 2> /dev/null ) 1> /dev/null
     if test -e tools/mpi2_test.o ; then
       echo "  " MPI_Comm_f2c and MPI_Comm_c2f are supported
-      sed '/^CC .*=/s/$/ -DMPI2_SUPPORT/' configure.wrf > xx$$ ; /bin/mv xx$$ configure.wrf
+      sed '/^DM_CC.*=/s/$/ -DMPI2_SUPPORT/' configure.wrf > xx$$ ; /bin/mv xx$$ configure.wrf
     else
       echo "  " MPI_Comm_f2c and MPI_Comm_c2f are not supported
     fi
@@ -401,6 +445,6 @@ echo "------------------------------------------------------------------------"
 echo "Settings listed above are written to configure.wrf."
 echo "If you wish to change settings, please edit that file."
 echo "If you wish to change the default options, edit the file:"
-echo "     arch/configure.defaults"
+echo "     arch/configure_new.defaults"
 echo " "
 
