Removing the remnants of the old, unused, WRFV2 configure system. (#308)
TYPE: feature removed

KEYWORDS: configure, WRFV4

SOURCE: Internal

DESCRIPTION OF CHANGES:
Prior to the WRFV3.0 release, John Michalakes implemented a "New, less insane configure mechanism and database" (commit f417280). This (and a few subsequent commits) greatly improved the organization of the configure system, but it kept a lot of legacy code around that has not been maintained for 10 or more years at this point, in the form of files renamed "*_old". These files have served their time faithfully, and have earned a retirement to a nice family on a farm in the country.

Should not affect anyone who isn't running on an incredibly obsolete system. Most of these scripts are completely unused, and the ones that are used are only for old, obsolete systems.

Here are the configurations that are lost in this change (there are others in that file as well but they have all been superseded by stanzas in configure_new.defaults):

 - SGI IRIX, according to Wikipedia, "last major version of IRIX was IRIX 6.5, which was released in May 1998"
 - SunOS, the last release of which was Nov 1994!
 - Compaq OSF1 alpha, an implementation of Tru64 UNIX, sold by Compaq in 2002 and officially discontinued in 2010
 - Alpha Linux alpha, seems to be related to the above OS; "Alpha" is actually a processor type not an OS, so I'm unsure what this stanza is supposed to apply to
 - UNIX_System_V, "one of the first commercial versions of the Unix operating system... first released in 1983". Forms the basis of many modern Unix-based systems, but is not its own OS anymore.
 - HP-UX PA8600 32bit. HP-UX introduced 64-bit support in 1997, people should have upgraded by now
 - HP-UX Itanium2. Itanium2 was an HP chip used from 2002-2010.
 - PC Interix A Windows-based thing that was discontinued/assimilated by Microsoft in 2002

And finally, now that there's a release repository, users can always just go find these long-lost, unmaintained files if they absolutely need them.

LIST OF MODIFIED FILES:
D arch/Config.pl
D arch/Config_old.pl
D arch/archive_configure.defaults
D arch/config_old
D arch/configure_old.defaults
D arch/postamble_old
D arch/preamble_old
M configure

TESTS CONDUCTED: New Cheyenne WTF passed (gnu and intel). WTF on all this week's changes on Yellowstone also passed (gnu, intel, pgi).

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -660,17 +660,12 @@ if test -n "$PERL" ; then
        /bin/mv configure.wrf.edit configure.wrf
      fi
    else
-     WRF_OS=$os ; export WRF_OS
-     WRF_MACH=$mach ; export WRF_MACH
-     echo '*** Configuration not found in configure_new.defaults; checking configure_old.defaults ***'
-
-     # see if we still have an old setting laying around from v2
-     if [ "$opt_level" = "-d" ] ; then
-       arch/config_old $opt_level 
-     else
-       arch/config_old
-     fi
-
+     echo '*********************************************************'
+     echo '***              ERROR ERROR ERROR ERROR              ***'
+     echo '***                                                   ***'
+     echo '*** Configuration not found in configure_new.defaults ***'
+     echo '*********************************************************'
+     exit 2
    fi
 fi
 
